markdown: kramdown
permalink: /:title/
url: 
name: 
author: CuiHaozhi
qq: 61755280
email: haozhi.cui@gmail.com
duoshuo: 
beian:
cnzz: 
weibo: 
github: sak0
safe: true
paginate: 20
about: "What are you doing here?"
